name: Package Test
on: push

jobs:

  black:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          pip install black
          black --check .
        
  pytest:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          pip install matplotlib requests IPython pytest bibtexparser
          pytest .
